import type { ProfileInput } from './types.js';

const ENV_KEY = /^[A-Za-z_][A-Za-z0-9_]*$/;

export function slugifyProfile(value: string): string {
  const slug = value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
  return slug || 'workspace';
}

export function serverNameForProfile(profile: string): string {
  return `rocketchat-${slugifyProfile(profile)}`;
}

export function buildProfileEnvironment(input: ProfileInput): Record<string, string> {
  return {
    ROCKETCHAT_BASE_URL: input.baseUrl,
    ROCKETCHAT_USER_ID: input.userId,
    ROCKETCHAT_AUTH_TOKEN: input.authToken,
    ROCKETCHAT_WORKSPACE_NAME: input.workspaceName,
    ROCKETCHAT_ALLOWED_ROOMS: input.roomAccess === 'all' ? '' : uniqueCsv(input.selectedRoomIds),
    ROCKETCHAT_ALLOW_DM: input.dmAccess === 'disabled' ? 'false' : 'true',
    ROCKETCHAT_ALLOWED_DM_USERS:
      input.dmAccess === 'selected' ? uniqueCsv(input.selectedDmUsers) : '',
    ROCKETCHAT_ALLOW_HERE_MENTION: input.mentionPolicy === 'blocked' ? 'false' : 'true',
    ROCKETCHAT_ALLOW_ALL_MENTION: input.mentionPolicy === 'all' ? 'true' : 'false',
    ROCKETCHAT_DISABLE_URL_PREVIEW: 'true',
    ROCKETCHAT_ALLOWED_UPLOAD_PATHS:
      input.uploadAccess === 'all'
        ? '/'
        : input.uploadAccess === 'selected'
          ? uniqueCsv(input.allowedUploadPaths)
          : '',
    ROCKETCHAT_MAX_UPLOAD_BYTES: String(25 * 1024 * 1024),
    MCP_TRANSPORT: 'stdio',
    LOG_LEVEL: 'info',
  };
}

export function renderProfileEnvironment(env: Record<string, string>): string {
  const groups: Array<{ heading: string; keys: string[] }> = [
    {
      heading: 'Rocket.Chat connection',
      keys: [
        'ROCKETCHAT_BASE_URL',
        'ROCKETCHAT_USER_ID',
        'ROCKETCHAT_AUTH_TOKEN',
        'ROCKETCHAT_WORKSPACE_NAME',
      ],
    },
    {
      heading: 'Destination policy',
      keys: ['ROCKETCHAT_ALLOWED_ROOMS', 'ROCKETCHAT_ALLOW_DM', 'ROCKETCHAT_ALLOWED_DM_USERS'],
    },
    {
      heading: 'Mention and content policy',
      keys: [
        'ROCKETCHAT_ALLOW_HERE_MENTION',
        'ROCKETCHAT_ALLOW_ALL_MENTION',
        'ROCKETCHAT_DISABLE_URL_PREVIEW',
      ],
    },
    {
      heading: 'Local file upload policy',
      keys: ['ROCKETCHAT_ALLOWED_UPLOAD_PATHS', 'ROCKETCHAT_MAX_UPLOAD_BYTES'],
    },
    { heading: 'Runtime', keys: ['MCP_TRANSPORT', 'LOG_LEVEL'] },
  ];

  const lines = [
    '# Generated by create-rocketchat-mcp.',
    '# System environment variables override values in this file.',
  ];
  for (const group of groups) {
    lines.push('', `# ${group.heading}`);
    for (const key of group.keys) {
      if (Object.prototype.hasOwnProperty.call(env, key)) {
        lines.push(`${key}=${quoteEnv(env[key] ?? '')}`);
      }
    }
  }
  return lines.join('\n') + '\n';
}

export function parseProfileEnvironment(content: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const rawLine of content.split(/\r?\n/)) {
    let line = rawLine.trim();
    if (line === '' || line.startsWith('#')) continue;
    if (line.startsWith('export ')) line = line.slice(7).trim();
    const equals = line.indexOf('=');
    if (equals === -1) continue;
    const key = line.slice(0, equals).trim();
    if (!ENV_KEY.test(key)) continue;
    let value = line.slice(equals + 1).trim();
    if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
      value = value.slice(1, -1).replace(/\\"/g, '"').replace(/\\n/g, '\n');
    } else if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

function quoteEnv(value: string): string {
  if (
    Array.from(value).some((character) => {
      const codePoint = character.codePointAt(0);
      return codePoint !== undefined && (codePoint <= 0x1f || codePoint === 0x7f);
    })
  ) {
    throw new Error('Environment values must not contain control characters.');
  }
  return `"${value.replace(/"/g, '\\"')}"`;
}

function uniqueCsv(values: string[]): string {
  return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean))).join(',');
}
